name: Test example files are working with GitHub models

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    # Also run when chat.py files are modified
    paths:
      - 'chat.py'
      - 'spanish/chat.py'
      - 'requirements.txt'
      - '.github/workflows/test-github-models.yaml'

jobs:
  test-github-models:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python_file:
          - "chat.py"
          - "spanish/chat.py"

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt

      - name: Test ${{ matrix.python_file }} with GitHub Models
        env:
          API_HOST: github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_MODEL: openai/gpt-4o-mini
        run: |
          python ${{ matrix.python_file }}
