name: Test GitHub Models

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    # Also run when chat.py files are modified
    paths:
      - 'chat.py'
      - 'spanish/chat.py'
      - 'requirements.txt'
      - '.github/workflows/test-github-models.yaml'

jobs:
  test-github-models:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test main chat.py with GitHub Models
        env:
          API_HOST: github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_MODEL: gpt-4o-mini
        run: |
          echo "Testing main chat.py file..."
          python chat.py

      - name: Test Spanish chat.py with GitHub Models
        env:
          API_HOST: github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_MODEL: gpt-4o-mini
        run: |
          echo "Testing Spanish chat.py file..."
          python spanish/chat.py
